Repository betagouv/lab-anssi-ui-kit, pull requests merged in 2025-05, with the labels that each got.

#46 1. Créé un composant réutilisable Brique pour les pages vitrines
  src/lib/lab/vitrines-produits/briques/Brique.svelte
  src/variables.scss
  stories/OutilSelecteurTheme.svelte
  stories/lab/vitrines-produits/briques/Brique.story.svelte
Labels: enhancement

#63 [CORRECTION] Rétablis le déploiement correct du Storybook
  package-lock.json
  package.json
  vite.config.ts
Labels: bug, enhancement

#64 [CORRECTION] Ajuste les marges laterales et verticales du carrousel de tuiles
  src/lib/lab/vitrines-produits/briques/Brique.svelte
  src/lib/lab/vitrines-produits/briques/CarrouselTuiles.svelte
  src/lib/lab/vitrines-produits/briques/Tuile.svelte
Labels: bug, enhancement

#65 [CORRECTION] Adapte la largeur de la vidéo en fonction d'une taille maximale
  src/lib/lab/vitrines-produits/briques/LecteurVideo.svelte
  stories/lab/vitrines-produits/LandingMAC.story.svelte
  stories/lab/vitrines-produits/briques/BriqueTitreMultimedia.story.svelte
Labels: bug, enhancement

#70 Corrige les largeurs de l’alerte
  src/lib/Alerte.svelte
Labels: bug

#71 [VERSION] Passe à la version 1.10.1
  package-lock.json
  package.json
Labels: enhancement
