Repository betagouv/lab-anssi-ui-kit, pull requests merged in 2025-03, with the labels that each got.

#7 [CI/CD] Ajoute une action de déploiement du storybook
  .github/workflows/publication-storybook.yml
  histoire.config.ts
Labels: enhancement

#10 Vérifie le fichier `JSX` généré
  outils/vite-plugin-genere-jsx.ts
Labels: enhancement

#11 Prend en compte le cas des composants sans "props"
  outils/vite-plugin-genere-jsx.ts
Labels: bug

#19 Ajoute la possibilité d'utiliser la variable d'environnement de chemin d'assets
  src/assets.scss
  vite.config.ts
Labels: enhancement

#18 Ajoute un outillage permettant d'injecter des `nonce` dans les balises de style
  outils/vite-plugin-injecte-nonce.ts
  vite.webcomponents.config.ts
Labels: enhancement

#23 Met à jour le fichier README
  README.md
Labels: enhancement

#25 [Version] Passe en 1.2.0
  package-lock.json
  package.json
Labels: release

#27 [VERSION] Publie la version 1.2.1
  package.json
Labels: release

#28 Correctifs sur la suite cyber pour l'intégration dans les différentes applications du Lab
  src/lib/suite-cyber/navigation/Navigation.svelte
Labels: enhancement

#29 [VERSION] Passe en 1.2.2
  package.json
Labels: release

#32 [CORRECTION] Corrige la story du centre d'aide
  stories/CentreAide.story.svelte
Labels: bug

#33 Ajoute une page de documentation
  stories/Documentation.story.svelte
  stories/OutilSelecteurTheme.svelte
  stories/icones/IconeCopier.svelte
Labels: documentation

#34 Fais remonter un évènement lors du clic sur un lien du centre d'aide
  src/lib/CentreAide.svelte
  stories/CentreAide.story.svelte
Labels: enhancement

#35 [VERSION] Passe en 1.3.1
  package.json
Labels: release
